// prisma/seed-data.ts — Realistic seed data for 5 shops × 7 garments
import type { ConditionGrade, EventTheme, BodyType } from "@prisma/client";

export const OWNERS = [
    { phone: "02055552001", name: "Owner Saengdao", shopIdx: 0 },
    { phone: "02055552002", name: "Owner Vilai", shopIdx: 1 },
    { phone: "02055552003", name: "Owner Thansamai", shopIdx: 2 },
    { phone: "02055552004", name: "Owner Dokjampa", shopIdx: 3 },
    { phone: "02055552005", name: "Owner Lao Lux", shopIdx: 4 },
] as const;

export const SHOPS = [
    { nameLo: "ຮ້ານ ແສງດາວ ບູຕິກ", nameEn: "Saengdao Boutique", description: "ຊຸດເດສ ລະດັບພຣີມຽມ ສຳລັບງານ Gala", phone: "02055552001", isVerified: true },
    { nameLo: "ຮ້ານ ວິໄລ ສິ້ນໄໝ", nameEn: "Vilai Silk Studio", description: "ສິ້ນໄໝແທ້ ແລະ ຊຸດປະເພນີ ທໍດ້ວຍມື", phone: "02055552002", isVerified: true },
    { nameLo: "ຮ້ານ ທັນສະໄໝ ເມັນ", nameEn: "Thansamai Menswear", description: "ຊຸດສູດ ແລະ ເຄື່ອງນຸ່ງຜູ້ຊາຍ ລະດັບສູງ", phone: "02055552003", isVerified: true },
    { nameLo: "ຮ້ານ ດອກຈຳປາ ເວດດິ້ງ", nameEn: "Dokjampa Wedding", description: "ຊຸດແຕ່ງງານ ເຈົ້າສາວ ເຈົ້າບ່າວ ຄົບວົງຈອນ", phone: "02055552004", isVerified: true },
    { nameLo: "ຮ້ານ ແຟຊັ່ນ ລາວລຸກ", nameEn: "Lao Lux Fashion", description: "ຊຸດ Premium ແລະ Costume ລະດັບສາກົນ", phone: "02055552005", isVerified: false },
] as const;

// categorySlug: dress=0, sinh=1, suit=2, traditional=3, accessories=4
export interface GarmentSeed {
    code: string; titleLo: string; titleEn: string; description: string;
    size: string; color: string; colorHex: string; brand: string;
    rentalPrice: number; deposit: number; isFeatured: boolean;
    conditionGrade: ConditionGrade; defectNotes?: string;
    bustMin: number; bustMax: number; waistMin: number; waistMax: number;
    hipMin: number; hipMax: number; heightMin?: number; heightMax?: number;
    eventThemes: EventTheme[]; bodyTypes: BodyType[];
    backupSizeFee?: number; bufferDays: number;
    catIdx: number; shopIdx: number; image: string;
}

export const GARMENTS: GarmentSeed[] = [
    // ═══ Shop 0: Saengdao Boutique (Dress/Gala) ═══
    { code: "SD-001", titleLo: "ເດສ ລາຕຣີ ສີນ້ຳເງິນ ປະດັບຄຣິສຕັນ", titleEn: "Blue Crystal Evening Gown", description: "ຊຸດລາຕຣີສີນ້ຳເງິນ ປະດັບຄຣິສຕັນ ເໝາະສຳລັບງານ Gala", size: "S", color: "Blue", colorHex: "#1E40AF", brand: "Saengdao Premium", rentalPrice: 550000, deposit: 1650000, isFeatured: true, conditionGrade: "A_PLUS", bustMin: 80, bustMax: 84, waistMin: 60, waistMax: 64, hipMin: 86, hipMax: 90, heightMin: 155, heightMax: 165, eventThemes: ["GALA"], bodyTypes: ["PETITE"], backupSizeFee: 50000, bufferDays: 2, catIdx: 0, shopIdx: 0, image: "sd001-blue-crystal-gown.png" },
    { code: "SD-002", titleLo: "ເດສ A-Line ສີດຳ Elegant", titleEn: "Black A-Line Elegant Dress", description: "ຊຸດເດສ A-Line ສີດຳ ທັນສະໄໝ ເໝາະທັງ Gala ແລະ Business", size: "M", color: "Black", colorHex: "#1A1A1A", brand: "Saengdao Premium", rentalPrice: 400000, deposit: 1200000, isFeatured: false, conditionGrade: "A", bustMin: 86, bustMax: 90, waistMin: 66, waistMax: 70, hipMin: 92, hipMax: 96, heightMin: 158, heightMax: 172, eventThemes: ["GALA", "BUSINESS"], bodyTypes: ["STANDARD"], bufferDays: 2, catIdx: 0, shopIdx: 0, image: "sd002-black-aline-dress.png" },
    { code: "SD-003", titleLo: "ເດສ ຍາວ ສີແດງ Wine ເປີດໄຫລ່", titleEn: "Wine Red Off-Shoulder Gown", description: "ຊຸດລາຕຣີ ສີແດງ Wine ເປີດໄຫລ່ ມີຫາງຍາວ", size: "L", color: "Wine Red", colorHex: "#722F37", brand: "Saengdao Couture", rentalPrice: 650000, deposit: 1950000, isFeatured: true, conditionGrade: "A_PLUS", bustMin: 92, bustMax: 98, waistMin: 72, waistMax: 78, hipMin: 98, hipMax: 104, heightMin: 160, heightMax: 175, eventThemes: ["GALA", "BRIDAL_PARTY"], bodyTypes: ["STANDARD", "CURVY"], backupSizeFee: 60000, bufferDays: 2, catIdx: 0, shopIdx: 0, image: "sd003-wine-red-gown.png" },
    { code: "SD-004", titleLo: "ເດສ Cocktail ສີບົວ ສັ້ນ", titleEn: "Pink Cocktail Dress", description: "ຊຸດ Cocktail ສີບົວ ສັ້ນ ເໝາະສຳລັບງານລ້ຽງ", size: "S", color: "Pink", colorHex: "#F9A8D4", brand: "Saengdao", rentalPrice: 350000, deposit: 1050000, isFeatured: false, conditionGrade: "B", defectNotes: "ມີຮອຍເປື້ອນເລັກໜ້ອຍ ດ້ານໃນ", bustMin: 80, bustMax: 84, waistMin: 60, waistMax: 64, hipMin: 86, hipMax: 90, heightMin: 152, heightMax: 165, eventThemes: ["GALA", "GRADUATION"], bodyTypes: ["PETITE"], bufferDays: 1, catIdx: 0, shopIdx: 0, image: "sd004-pink-cocktail.png" },
    { code: "SD-005", titleLo: "ເດສ ສີຂາວ ຕົກແຕ່ງລູກໄມ້", titleEn: "White Lace Evening Dress", description: "ຊຸດເດສ ສີຂາວ ລູກໄມ້ຝຣັ່ງເສດ ງົດງາມ", size: "M", color: "White", colorHex: "#FFFAF0", brand: "Saengdao Couture", rentalPrice: 500000, deposit: 1500000, isFeatured: true, conditionGrade: "A", bustMin: 86, bustMax: 90, waistMin: 66, waistMax: 70, hipMin: 92, hipMax: 96, heightMin: 158, heightMax: 172, eventThemes: ["WEDDING", "GALA"], bodyTypes: ["STANDARD"], backupSizeFee: 50000, bufferDays: 2, catIdx: 0, shopIdx: 0, image: "sd005-white-lace-dress.png" },
    { code: "SD-006", titleLo: "ຊຸດເຈົ້າສາວ ສີຂາວ ຫາງ 2m", titleEn: "White Bridal Gown with Train", description: "ຊຸດເຈົ້າສາວ ສີຂາວ ຫາງ 2 ແມັດ ລູກໄມ້ປ້ອງ", size: "M", color: "White", colorHex: "#FFFFFF", brand: "Saengdao Bridal", rentalPrice: 800000, deposit: 2400000, isFeatured: true, conditionGrade: "A_PLUS", bustMin: 84, bustMax: 90, waistMin: 64, waistMax: 70, hipMin: 90, hipMax: 96, heightMin: 158, heightMax: 170, eventThemes: ["WEDDING"], bodyTypes: ["STANDARD", "PETITE"], backupSizeFee: 80000, bufferDays: 3, catIdx: 0, shopIdx: 0, image: "sd006-white-bridal-gown.png" },
    { code: "SD-007", titleLo: "ກະເປົ໋າ Clutch ສີຄຳ ປະດັບເພັດ", titleEn: "Gold Crystal Clutch Bag", description: "ກະເປົ໋າ Clutch ສີຄຳ ປະດັບ CZ ເໝາະງານ Gala", size: "FREE", color: "Gold", colorHex: "#FFD700", brand: "Saengdao", rentalPrice: 120000, deposit: 360000, isFeatured: false, conditionGrade: "A", bustMin: 0, bustMax: 0, waistMin: 0, waistMax: 0, hipMin: 0, hipMax: 0, eventThemes: ["GALA", "WEDDING"], bodyTypes: [], bufferDays: 1, catIdx: 4, shopIdx: 0, image: "sd007-gold-clutch.png" },

    // ═══ Shop 1: Vilai Silk Studio (Sinh/Traditional) ═══
    { code: "VL-001", titleLo: "ສິ້ນໄໝ ລາຍນາກ ສີຄຳ ທໍມື", titleEn: "Gold Naga Silk Sinh", description: "ສິ້ນໄໝແທ້ ລາຍນາກ ສີຄຳ ທໍດ້ວຍມື", size: "FREE", color: "Red & Gold", colorHex: "#C41E3A", brand: "Vilai Handmade", rentalPrice: 280000, deposit: 840000, isFeatured: true, conditionGrade: "A", bustMin: 80, bustMax: 100, waistMin: 60, waistMax: 85, hipMin: 88, hipMax: 108, eventThemes: ["TEMPLE", "WEDDING"], bodyTypes: ["STANDARD", "CURVY", "PLUS_SIZE"], backupSizeFee: 30000, bufferDays: 1, catIdx: 1, shopIdx: 1, image: "vl001-gold-silk-sinh.png" },
    { code: "VL-002", titleLo: "ສິ້ນໄໝ ສີມ່ວງ ດອກພິກຸນ", titleEn: "Purple Pikun Silk Sinh", description: "ສິ້ນໄໝ ສີມ່ວງ ລາຍດອກພິກຸນ ທໍເງິນ-ຄຳ", size: "FREE", color: "Purple", colorHex: "#6B21A8", brand: "Vilai Handmade", rentalPrice: 220000, deposit: 660000, isFeatured: false, conditionGrade: "A", bustMin: 78, bustMax: 96, waistMin: 58, waistMax: 78, hipMin: 86, hipMax: 100, eventThemes: ["TEMPLE", "GRADUATION"], bodyTypes: ["STANDARD", "PETITE"], bufferDays: 1, catIdx: 1, shopIdx: 1, image: "vl002-purple-silk-sinh.png" },
    { code: "VL-003", titleLo: "ຊຸດປະເພນີ ສີຂຽວມໍລະກົດ ຄົບຊຸດ", titleEn: "Emerald Traditional Set", description: "ຊຸດປະເພນີ ສີຂຽວ ຄົບຊຸດ ສິ້ນ+ເສື້ອ+ສະໄບ", size: "M", color: "Emerald & Gold", colorHex: "#047857", brand: "Vilai Heritage", rentalPrice: 380000, deposit: 1140000, isFeatured: true, conditionGrade: "A_PLUS", bustMin: 84, bustMax: 92, waistMin: 64, waistMax: 72, hipMin: 90, hipMax: 98, heightMin: 155, heightMax: 170, eventThemes: ["TEMPLE", "WEDDING"], bodyTypes: ["STANDARD"], backupSizeFee: 40000, bufferDays: 1, catIdx: 3, shopIdx: 1, image: "vl003-emerald-traditional.png" },
    { code: "VL-004", titleLo: "ຊຸດປະເພນີ ສີບົວທອງ ງານບຸນ", titleEn: "Pink Gold Temple Set", description: "ຊຸດປະເພນີ ສີບົວ-ຄຳ ເໝາະງານບຸນ ໄຊສ໌ໃຫຍ່", size: "L", color: "Pink & Gold", colorHex: "#F9A8D4", brand: "Vilai Heritage", rentalPrice: 320000, deposit: 960000, isFeatured: false, conditionGrade: "A", bustMin: 92, bustMax: 104, waistMin: 76, waistMax: 88, hipMin: 100, hipMax: 112, heightMin: 155, heightMax: 175, eventThemes: ["TEMPLE"], bodyTypes: ["CURVY", "PLUS_SIZE"], bufferDays: 1, catIdx: 3, shopIdx: 1, image: "vl004-pink-gold-traditional.png" },
    { code: "VL-005", titleLo: "ສິ້ນ ຜ້າຝ້າຍ ສີນ້ຳຕານ ລາຍດອກ", titleEn: "Brown Cotton Floral Sinh", description: "ສິ້ນ ຜ້າຝ້າຍ ສີນ້ຳຕານ ລາຍດອກ ໃສ່ທຸກວັນ", size: "FREE", color: "Brown", colorHex: "#92400E", brand: "Vilai Casual", rentalPrice: 150000, deposit: 450000, isFeatured: false, conditionGrade: "B", bustMin: 80, bustMax: 100, waistMin: 60, waistMax: 85, hipMin: 88, hipMax: 108, eventThemes: ["TEMPLE", "OTHER"], bodyTypes: ["STANDARD", "CURVY"], bufferDays: 1, catIdx: 1, shopIdx: 1, image: "vl005-brown-cotton-sinh.png" },
    { code: "VL-006", titleLo: "ສະໄບ ໄໝແທ້ ສີຄຳ ປັກດ້ວຍມື", titleEn: "Gold Silk Sabai Sash", description: "ສະໄບ ໄໝແທ້ ສີຄຳ ປັກດ້ວຍມື ງານ Wedding/Temple", size: "FREE", color: "Gold", colorHex: "#D4AF37", brand: "Vilai Handmade", rentalPrice: 180000, deposit: 540000, isFeatured: false, conditionGrade: "A_PLUS", bustMin: 0, bustMax: 0, waistMin: 0, waistMax: 0, hipMin: 0, hipMax: 0, eventThemes: ["WEDDING", "TEMPLE"], bodyTypes: [], bufferDays: 1, catIdx: 4, shopIdx: 1, image: "vl006-gold-silk-sabai.png" },
    { code: "VL-007", titleLo: "ຊຸດລາວ ສີແດງ ງານດອງ ຄົບຊຸດ", titleEn: "Red Lao Wedding Set", description: "ຊຸດລາວ ສີແດງ-ຄຳ ງານດອງ ຄົບຊຸດ", size: "S", color: "Red & Gold", colorHex: "#DC2626", brand: "Vilai Bridal", rentalPrice: 400000, deposit: 1200000, isFeatured: true, conditionGrade: "A", bustMin: 80, bustMax: 86, waistMin: 60, waistMax: 66, hipMin: 86, hipMax: 92, heightMin: 152, heightMax: 164, eventThemes: ["WEDDING"], bodyTypes: ["PETITE"], bufferDays: 1, catIdx: 3, shopIdx: 1, image: "vl007-red-wedding-lao.png" },

    // ═══ Shop 2: Thansamai Menswear (Suit/Business) ═══
    { code: "TM-001", titleLo: "ຊຸດສູດ Slim Fit ສີດຳ 3 ຊິ້ນ", titleEn: "Black Slim Fit Three-Piece Suit", description: "ຊຸດສູດ 3 ຊິ້ນ ສີດຳ Slim Fit ລະດັບ Premium", size: "M", color: "Black", colorHex: "#1A1A1A", brand: "Thansamai Bespoke", rentalPrice: 500000, deposit: 1500000, isFeatured: true, conditionGrade: "A_PLUS", bustMin: 92, bustMax: 100, waistMin: 76, waistMax: 84, hipMin: 96, hipMax: 104, heightMin: 165, heightMax: 180, eventThemes: ["BUSINESS", "GALA"], bodyTypes: ["STANDARD"], backupSizeFee: 50000, bufferDays: 2, catIdx: 2, shopIdx: 2, image: "tm001-black-slim-suit.png" },
    { code: "TM-002", titleLo: "ຊຸດສູດ ສີເທົາ Double-Breasted", titleEn: "Grey Double-Breasted Suit", description: "ຊຸດສູດ ສີເທົາ Double-Breasted ສະໄຕລ໌ຄລາສິກ", size: "L", color: "Grey", colorHex: "#4B5563", brand: "Thansamai Classic", rentalPrice: 450000, deposit: 1350000, isFeatured: false, conditionGrade: "A", bustMin: 100, bustMax: 108, waistMin: 84, waistMax: 92, hipMin: 104, hipMax: 112, heightMin: 170, heightMax: 188, eventThemes: ["BUSINESS", "GRADUATION"], bodyTypes: ["STANDARD", "TALL"], bufferDays: 2, catIdx: 2, shopIdx: 2, image: "tm002-grey-double-breasted.png" },
    { code: "TM-003", titleLo: "ຊຸດສູດ ສີຂາວ Tuxedo ງານແຕ່ງ", titleEn: "White Wedding Tuxedo", description: "ຊຸດ Tuxedo ສີຂາວ ງານແຕ່ງ ມາພ້ອມ Bow Tie", size: "M", color: "White", colorHex: "#FFFFF0", brand: "Thansamai Bridal", rentalPrice: 600000, deposit: 1800000, isFeatured: true, conditionGrade: "A_PLUS", bustMin: 92, bustMax: 100, waistMin: 76, waistMax: 84, hipMin: 96, hipMax: 104, heightMin: 168, heightMax: 182, eventThemes: ["WEDDING", "GALA"], bodyTypes: ["STANDARD"], backupSizeFee: 60000, bufferDays: 2, catIdx: 2, shopIdx: 2, image: "tm003-white-tuxedo.png" },
    { code: "TM-004", titleLo: "ເສື້ອ Blazer ສີກົມ ໃສ່ທຸກວັນ", titleEn: "Navy Smart Casual Blazer", description: "ເສື້ອ Blazer ສີກົມ Smart Casual ໃສ່ທຸກວັນ", size: "XL", color: "Navy", colorHex: "#1E3A5F", brand: "Thansamai Casual", rentalPrice: 280000, deposit: 840000, isFeatured: false, conditionGrade: "B", bustMin: 108, bustMax: 120, waistMin: 92, waistMax: 104, hipMin: 112, hipMax: 124, heightMin: 175, heightMax: 192, eventThemes: ["BUSINESS"], bodyTypes: ["TALL", "PLUS_SIZE"], bufferDays: 1, catIdx: 2, shopIdx: 2, image: "tm004-navy-blazer.png" },
    { code: "TM-005", titleLo: "ເນັກໄທ ໄໝແທ້ ສີແດງ ລາຍທາງ", titleEn: "Red Silk Striped Necktie", description: "ເນັກໄທ ໄໝແທ້ ສີແດງ ລາຍທາງເບັ້ຍ", size: "FREE", color: "Red", colorHex: "#DC2626", brand: "Thansamai", rentalPrice: 80000, deposit: 240000, isFeatured: false, conditionGrade: "A", bustMin: 0, bustMax: 0, waistMin: 0, waistMax: 0, hipMin: 0, hipMax: 0, eventThemes: ["BUSINESS", "GRADUATION"], bodyTypes: [], bufferDays: 1, catIdx: 4, shopIdx: 2, image: "tm005-red-silk-tie.png" },
    { code: "TM-006", titleLo: "ຊຸດສູດ ສີນ້ຳຕານ Vintage", titleEn: "Brown Vintage Tweed Suit", description: "ຊຸດສູດ ສີນ້ຳຕານ Vintage Tweed 70s style", size: "L", color: "Brown", colorHex: "#92400E", brand: "Thansamai Vintage", rentalPrice: 380000, deposit: 1140000, isFeatured: false, conditionGrade: "C", defectNotes: "ຜ້າມີລອຍເກົ່າ ແບບ vintage ບໍ່ແມ່ນເສຍຫາຍ", bustMin: 96, bustMax: 104, waistMin: 80, waistMax: 88, hipMin: 100, hipMax: 108, heightMin: 168, heightMax: 182, eventThemes: ["BUSINESS", "OTHER"], bodyTypes: ["STANDARD"], bufferDays: 1, catIdx: 2, shopIdx: 2, image: "tm006-brown-vintage-suit.png" },
    { code: "TM-007", titleLo: "ເສື້ອ Vest ສີດຳ + ໂບ Tie ຄຳ", titleEn: "Black Vest & Gold Bow Tie Set", description: "ເສື້ອ Vest Formal ສີດຳ ມາພ້ອມ Bow Tie ສີຄຳ", size: "M", color: "Black & Gold", colorHex: "#1A1A1A", brand: "Thansamai", rentalPrice: 150000, deposit: 450000, isFeatured: false, conditionGrade: "A", bustMin: 92, bustMax: 100, waistMin: 76, waistMax: 84, hipMin: 96, hipMax: 104, eventThemes: ["GALA", "WEDDING"], bodyTypes: ["STANDARD"], bufferDays: 1, catIdx: 4, shopIdx: 2, image: "tm007-black-vest-bowtie.png" },

    // ═══ Shop 3: Dokjampa Wedding (Wedding specialist) ═══
    { code: "DJ-001", titleLo: "ຊຸດເຈົ້າສາວ ສີຂາວ Mermaid", titleEn: "White Mermaid Bridal Gown", description: "ຊຸດເຈົ້າສາວ ສີຂາວ ທຣົງ Mermaid ລູກໄມ້ປ້ອງ", size: "S", color: "White", colorHex: "#FFFFFF", brand: "Dokjampa Bridal", rentalPrice: 900000, deposit: 2700000, isFeatured: true, conditionGrade: "A_PLUS", bustMin: 80, bustMax: 86, waistMin: 60, waistMax: 66, hipMin: 86, hipMax: 92, heightMin: 155, heightMax: 168, eventThemes: ["WEDDING"], bodyTypes: ["PETITE", "STANDARD"], backupSizeFee: 80000, bufferDays: 3, catIdx: 0, shopIdx: 3, image: "dj001-white-mermaid-bridal.png" },
    { code: "DJ-002", titleLo: "ຊຸດເຈົ້າສາວ ສີຄຳ A-Line", titleEn: "Gold A-Line Bridal Gown", description: "ຊຸດເຈົ້າສາວ ສີຄຳ A-Line ປັກດ້ວຍມື", size: "M", color: "Champagne Gold", colorHex: "#D4AF37", brand: "Dokjampa Bridal", rentalPrice: 750000, deposit: 2250000, isFeatured: true, conditionGrade: "A_PLUS", bustMin: 86, bustMax: 92, waistMin: 66, waistMax: 72, hipMin: 92, hipMax: 98, heightMin: 158, heightMax: 172, eventThemes: ["WEDDING"], bodyTypes: ["STANDARD", "CURVY"], backupSizeFee: 70000, bufferDays: 3, catIdx: 0, shopIdx: 3, image: "dj002-gold-aline-bridal.png" },
    { code: "DJ-003", titleLo: "ຊຸດເພື່ອນເຈົ້າສາວ ສີມ່ວງ", titleEn: "Purple Bridesmaid Dress", description: "ຊຸດເພື່ອນເຈົ້າສາວ ສີມ່ວງ ຜ້າ Chiffon", size: "M", color: "Purple", colorHex: "#6B21A8", brand: "Dokjampa Party", rentalPrice: 350000, deposit: 1050000, isFeatured: false, conditionGrade: "A", bustMin: 86, bustMax: 92, waistMin: 66, waistMax: 72, hipMin: 92, hipMax: 98, heightMin: 158, heightMax: 172, eventThemes: ["BRIDAL_PARTY"], bodyTypes: ["STANDARD"], bufferDays: 2, catIdx: 0, shopIdx: 3, image: "dj003-purple-bridesmaid.png" },
    { code: "DJ-004", titleLo: "ຊຸດເພື່ອນເຈົ້າສາວ ສີບົວ", titleEn: "Pink One-Shoulder Bridesmaid", description: "ຊຸດເພື່ອນເຈົ້າສາວ ສີບົວ ໄຫລ່ດຽວ", size: "L", color: "Pink", colorHex: "#F9A8D4", brand: "Dokjampa Party", rentalPrice: 350000, deposit: 1050000, isFeatured: false, conditionGrade: "A", bustMin: 92, bustMax: 98, waistMin: 72, waistMax: 78, hipMin: 98, hipMax: 104, heightMin: 160, heightMax: 175, eventThemes: ["BRIDAL_PARTY"], bodyTypes: ["CURVY"], bufferDays: 2, catIdx: 0, shopIdx: 3, image: "dj004-pink-bridesmaid.png" },
    { code: "DJ-005", titleLo: "ຊຸດພິທີ ລາວ ເຈົ້າບ່າວ ສີຂາວ", titleEn: "Lao Groom White Ceremony Set", description: "ຊຸດພິທີ ເຈົ້າບ່າວ ສີຂາວ-ຄຳ ແບບລາວ", size: "L", color: "White & Gold", colorHex: "#FFFFF0", brand: "Dokjampa Groom", rentalPrice: 500000, deposit: 1500000, isFeatured: false, conditionGrade: "A", bustMin: 100, bustMax: 108, waistMin: 84, waistMax: 92, hipMin: 104, hipMax: 112, heightMin: 170, heightMax: 185, eventThemes: ["WEDDING"], bodyTypes: ["STANDARD", "TALL"], bufferDays: 2, catIdx: 3, shopIdx: 3, image: "dj005-white-lao-groom.png" },
    { code: "DJ-006", titleLo: "ມົງກຸດ ເຈົ້າສາວ ເພັດ CZ", titleEn: "Bridal CZ Crystal Tiara", description: "ມົງກຸດ ເຈົ້າສາວ ເພັດ CZ ດີໄຊນ໌ ໃບໄມ້", size: "FREE", color: "Silver", colorHex: "#C0C0C0", brand: "Dokjampa Accessories", rentalPrice: 200000, deposit: 600000, isFeatured: false, conditionGrade: "A_PLUS", bustMin: 0, bustMax: 0, waistMin: 0, waistMax: 0, hipMin: 0, hipMax: 0, eventThemes: ["WEDDING", "BRIDAL_PARTY"], bodyTypes: [], bufferDays: 1, catIdx: 4, shopIdx: 3, image: "dj006-bridal-tiara.png" },
    { code: "DJ-007", titleLo: "ຊຸດ Flower Girl ສີຂາວ ເດັກ", titleEn: "White Flower Girl Dress", description: "ຊຸດ Flower Girl ສີຂາວ ສຳລັບເດັກ 4-8 ປີ", size: "S", color: "White", colorHex: "#FFFFFF", brand: "Dokjampa Kids", rentalPrice: 180000, deposit: 540000, isFeatured: false, conditionGrade: "A", bustMin: 56, bustMax: 68, waistMin: 48, waistMax: 58, hipMin: 60, hipMax: 72, heightMin: 100, heightMax: 130, eventThemes: ["WEDDING"], bodyTypes: ["PETITE"], bufferDays: 1, catIdx: 0, shopIdx: 3, image: "dj007-flower-girl-white.png" },

    // ═══ Shop 4: Lao Lux Fashion (Premium/Mixed/Costume) ═══
    { code: "LL-001", titleLo: "ເດສ Haute Couture ສີຟ້າ ເກັດປາ", titleEn: "Blue Sequin Haute Couture Dress", description: "ເດສ Haute Couture ສີຟ້າ ເກັດປາ ດີໄຊນ໌ Avant-Garde", size: "M", color: "Celestial Blue", colorHex: "#3B82F6", brand: "Lao Lux Couture", rentalPrice: 1200000, deposit: 3600000, isFeatured: true, conditionGrade: "A_PLUS", bustMin: 84, bustMax: 90, waistMin: 64, waistMax: 70, hipMin: 90, hipMax: 96, heightMin: 162, heightMax: 175, eventThemes: ["GALA", "COSTUME"], bodyTypes: ["STANDARD"], backupSizeFee: 100000, bufferDays: 3, catIdx: 0, shopIdx: 4, image: "ll001-blue-haute-couture.png" },
    { code: "LL-002", titleLo: "ຊຸດ Cosplay ກິໂມໂນ ສີແດງ", titleEn: "Red Kimono Cosplay Costume", description: "ກິໂມໂນ ສີແດງ ປັກດອກເບ່ັນໝາກ ຄຸນະພາບ Cosplay", size: "S", color: "Red & Gold", colorHex: "#B91C1C", brand: "Lao Lux Costume", rentalPrice: 250000, deposit: 750000, isFeatured: false, conditionGrade: "A", bustMin: 80, bustMax: 88, waistMin: 60, waistMax: 68, hipMin: 86, hipMax: 94, heightMin: 152, heightMax: 168, eventThemes: ["COSTUME", "OTHER"], bodyTypes: ["PETITE"], bufferDays: 1, catIdx: 3, shopIdx: 4, image: "ll002-red-kimono.png" },
    { code: "LL-003", titleLo: "ຊຸດ Mao ສີດຳ ປັກມັງກອນ", titleEn: "Black Dragon Mao Suit", description: "ຊຸດ Mao ສີດຳ ປັກມັງກອນ ຄຳ Fusion Style", size: "M", color: "Black & Gold", colorHex: "#1A1A1A", brand: "Lao Lux Fusion", rentalPrice: 350000, deposit: 1050000, isFeatured: false, conditionGrade: "A", bustMin: 92, bustMax: 100, waistMin: 76, waistMax: 84, hipMin: 96, hipMax: 104, heightMin: 165, heightMax: 180, eventThemes: ["GRADUATION", "OTHER"], bodyTypes: ["STANDARD"], bufferDays: 2, catIdx: 2, shopIdx: 4, image: "ll003-black-mao-suit.png" },
    { code: "LL-004", titleLo: "ຊຸດ Áo Dài ສີຂາວ ງານບຸນ", titleEn: "White Áo Dài Ceremony Dress", description: "ຊຸດ Áo Dài ສີຂາວ ປັກດອກ ເໝາະງານບຸນ/ຮັບປະລິນຍາ", size: "M", color: "White", colorHex: "#FAFAFA", brand: "Lao Lux Fusion", rentalPrice: 300000, deposit: 900000, isFeatured: false, conditionGrade: "A", bustMin: 84, bustMax: 90, waistMin: 64, waistMax: 70, hipMin: 90, hipMax: 96, heightMin: 158, heightMax: 172, eventThemes: ["TEMPLE", "GRADUATION"], bodyTypes: ["STANDARD"], bufferDays: 1, catIdx: 3, shopIdx: 4, image: "ll004-white-ao-dai.png" },
    { code: "LL-005", titleLo: "ເດສ ມິນິ ສີເງິນ Sequin ປາຕີ", titleEn: "Silver Sequin Party Mini Dress", description: "ເດສ ສີເງິນ Sequin ໄຊສ໌ XL ເໝາະປາຕີ", size: "XL", color: "Silver", colorHex: "#C0C0C0", brand: "Lao Lux Party", rentalPrice: 400000, deposit: 1200000, isFeatured: false, conditionGrade: "B", bustMin: 100, bustMax: 112, waistMin: 84, waistMax: 96, hipMin: 106, hipMax: 118, heightMin: 155, heightMax: 175, eventThemes: ["GALA", "COSTUME"], bodyTypes: ["PLUS_SIZE", "CURVY"], bufferDays: 1, catIdx: 0, shopIdx: 4, image: "ll005-silver-sequin-mini.png" },
    { code: "LL-006", titleLo: "ໂສ້ງຊຸດ Jumpsuit ສີດຳ Elegant", titleEn: "Black Elegant Jumpsuit", description: "ໂສ້ງຊຸດ Jumpsuit ສີດຳ ຂາກ້ວາງ Elegant", size: "L", color: "Black", colorHex: "#1A1A1A", brand: "Lao Lux Modern", rentalPrice: 350000, deposit: 1050000, isFeatured: false, conditionGrade: "A", bustMin: 90, bustMax: 98, waistMin: 70, waistMax: 78, hipMin: 96, hipMax: 104, heightMin: 165, heightMax: 180, eventThemes: ["BUSINESS", "GALA"], bodyTypes: ["TALL", "STANDARD"], bufferDays: 1, catIdx: 0, shopIdx: 4, image: "ll006-black-jumpsuit.png" },
    { code: "LL-007", titleLo: "ເຄື່ອງປະດັບ ຊຸດ 3 ຊິ້ນ ສີເງິນ", titleEn: "Silver 3-Piece Jewelry Set", description: "ເຄື່ອງປະດັບ ຊຸດ 3 ຊິ້ນ ສ້ອຍ+ຫູ+ກຳໄລ ສີເງິນ", size: "FREE", color: "Silver", colorHex: "#C0C0C0", brand: "Lao Lux", rentalPrice: 100000, deposit: 300000, isFeatured: false, conditionGrade: "B", bustMin: 0, bustMax: 0, waistMin: 0, waistMax: 0, hipMin: 0, hipMax: 0, eventThemes: ["GALA", "COSTUME"], bodyTypes: [], bufferDays: 1, catIdx: 4, shopIdx: 4, image: "ll007-silver-jewelry-set.png" },
];
